### ISSUE TITLE
频道定制

### ISSUE THREAD

**Issue by woailuoli** [mengxianliang/XLPageViewController#10]
选中当前title最后一个，然后进去频道选择。在里面删掉最后一个（也就是自己）会崩溃，奔溃点在下面
 NSIndexPath *indexPath1 = [NSIndexPath indexPathForRow:_selectedIndex inSection:0];
    NSIndexPath *indexPath2 = [NSIndexPath indexPathForRow:_lastSelectedIndex inSection:0];
    [UIView performWithoutAnimation:^{
                [self.collectionView reloadItemsAtIndexPaths:@[indexPath1,indexPath2]];
    }];

**Comment by mengxianliang** [comment]
这个问题改好了，更新一下代码吧。
