### ISSUE TITLE
空白页，及UIView flush crash

### ISSUE THREAD

**Issue by panwang** [mengxianliang/XLPageViewController#11]
1、只点击头部的titleview切换，快速来回切换，概率报UIView flush 的crash错误
2.一边滑动带有scrollview对象的viewcontroller.一边点击头部titleview。概率出现同1的问题，还有概率报”Duplicate states in queue'crash
3、点击titleview切换的时候，快速点viewcontroller对象，概率出现空白页，或者显示错乱问题
尝试修改内部实现，但是越该问题越多😹

**Comment by mengxianliang** [comment]
方便给一个能测试出这三个问题的Demo吗？
