### ISSUE TITLE
发现2个bug

### ISSUE THREAD

**Issue by EricsXcode** [mengxianliang/XLPageViewController#12]
bug1：多个titleview，从左到右滑动到最后一页，然后从右到左，会发现某一瞬间居中滚动动画失效。
bug2：多层级page，第一层级正常，第二层级（10个以上的页面）中titleview会乱跳，伴随着出现空白页，titleview异常选中。

**Comment by EricsXcode** [comment]
多层page滑动到最左边，继续向左滑动，理论上是第一级page滑动，先出现第一级和第二级page都会滑动。望楼主尽快解决这些问题。谢谢！

**Comment by mengxianliang** [comment]
这些问题已经解决了，更新一下代码吧。

**Comment by EricsXcode** [comment]
感谢 ！！！

**Comment by mengxianliang** [comment]
不客气哈
