### ISSUE TITLE
更新titleViewBackgroundColor的颜色并reloaddata后没有效果

### ISSUE THREAD

**Issue by MrHT** [mengxianliang/XLPageViewController#13]
更新titleViewBackgroundColor的颜色并reloaddata后没有效果

**Comment by mengxianliang** [comment]
您是想要在初始化pageViewController之后更新标题栏的背景色吧。
现在的设计思路是不支持这么做的，所有的外观只能在初始化时设置。

不过您可以把XLPageViewController里的titleView设置为公有属性，这样就可以在初始化后设置它背景颜色。
