### ISSUE TITLE
你好, 如何禁掉回弹的效果

### ISSUE THREAD

**Issue by lishangjing-spec** [mengxianliang/XLPageViewController#14]

**Comment by AlexLi1996** [comment]
我现在处理第一个界面的回弹是这样处理的: 

`
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    CGFloat value = scrollView.contentOffset.x - scrollView.bounds.size.width;
    self.titleView.animationProgress = value/scrollView.bounds.size.width;

    if(self.selectedIndex == 0 && self.pageVCAnimating == false){
        if(scrollView.contentOffset.x <= KScreenWidth){
            scrollView.scrollEnabled = false;
            [scrollView setContentOffset:CGPointMake(KScreenWidth, scrollView.contentOffset.y)];
        }else{
            scrollView.scrollEnabled = true;
        }
    }
}

`

**Comment by AlexLi1996** [comment]
我现在是这么处理的, 有没有更好的办法
`
-(void)scrollViewDidScroll:(UIScrollView *)scrollView {
    CGFloat value = scrollView.contentOffset.x - scrollView.bounds.size.width;
    self.titleView.animationProgress = value/scrollView.bounds.size.width;

    if(self.selectedIndex == 0 && self.pageVCAnimating == false){
        if(scrollView.contentOffset.x <= KScreenWidth){
            scrollView.scrollEnabled = false;
            [scrollView setContentOffset:CGPointMake(KScreenWidth, scrollView.contentOffset.y)];
        }else{
            scrollView.scrollEnabled = true;
        }
    }else if(self.selectedIndex == [self numberOfPage]-1 && self.pageVCAnimating == false){
        if(scrollView.contentOffset.x >= KScreenWidth){
            scrollView.scrollEnabled = false;
            [scrollView setContentOffset:CGPointMake(KScreenWidth, scrollView.contentOffset.y)];
        }else{
            scrollView.scrollEnabled = true;
        }
    }
}
`

**Comment by AlexLi1996** [comment]
我现在是这么处理的, 有没有更好的办法
`
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    CGFloat value = scrollView.contentOffset.x - scrollView.bounds.size.width;
    self.titleView.animationProgress = value/scrollView.bounds.size.width;
    if(self.selectedIndex == 0 && self.pageVCAnimating == false){
        if(scrollView.contentOffset.x <= KScreenWidth){
            scrollView.scrollEnabled = false;
            [scrollView setContentOffset:CGPointMake(KScreenWidth, scrollView.contentOffset.y)];
        }else{
            scrollView.scrollEnabled = true;
        }
    }else if(self.selectedIndex == [self numberOfPage]-1 && self.pageVCAnimating == false){
        if(scrollView.contentOffset.x >= KScreenWidth){
            scrollView.scrollEnabled = false;
            [scrollView setContentOffset:CGPointMake(KScreenWidth, scrollView.contentOffset.y)];
        }else{
            scrollView.scrollEnabled = true;
        }
    }
}
`

**Comment by AlexLi1996** [comment]
我现在是这么处理的, 有没有更好的办法

`
#pragma mark ScrollViewDelegate
//滚动时计算标题动画进度
-(void)scrollViewDidScroll:(UIScrollView *)scrollView {
    CGFloat value = scrollView.contentOffset.x - scrollView.bounds.size.width;
    self.titleView.animationProgress = value/scrollView.bounds.size.width;
    // 处理弹性
    if(self.selectedIndex == 0 && self.pageVCAnimating == false){
        if(scrollView.contentOffset.x <= KScreenWidth){
            scrollView.scrollEnabled = false;
            [scrollView setContentOffset:CGPointMake(KScreenWidth, scrollView.contentOffset.y)];
        }else{
            scrollView.scrollEnabled = true;
        }
    }else if(self.selectedIndex == [self numberOfPage]-1 && self.pageVCAnimating == false){
        if(scrollView.contentOffset.x >= KScreenWidth){
            scrollView.scrollEnabled = false;
            [scrollView setContentOffset:CGPointMake(KScreenWidth, scrollView.contentOffset.y)];
        }else{
            scrollView.scrollEnabled = true;
        }
    }
}
`

**Comment by lishangjing-spec** [comment]
我现在是这么处理的, 有没有更好的办法

```
-(void)scrollViewDidScroll:(UIScrollView *)scrollView {
    CGFloat value = scrollView.contentOffset.x - scrollView.bounds.size.width;
    self.titleView.animationProgress = value/scrollView.bounds.size.width;

    // 处理弹性
    if(self.selectedIndex == 0 && self.pageVCAnimating == false){
        if(scrollView.contentOffset.x <= [[UIScreen mainScreen] bounds].size.width){
            scrollView.scrollEnabled = false;
            [scrollView setContentOffset:CGPointMake([[UIScreen mainScreen] bounds].size.width, scrollView.contentOffset.y)];
        }else{
            scrollView.scrollEnabled = true;
        }
    }else if(self.selectedIndex == [self numberOfPage]-1 && self.pageVCAnimating == false){
        if(scrollView.contentOffset.x >= [[UIScreen mainScreen] bounds].size.width){
            scrollView.scrollEnabled = false;
            [scrollView setContentOffset:CGPointMake(KScreenWidth, scrollView.contentOffset.y)];
        }else{
            scrollView.scrollEnabled = true;
        }
    }
}
```

**Comment by mengxianliang** [comment]
能具体描述一下你想要实现什么样的回弹效果吗?

**Comment by lishangjing-spec** [comment]
想禁掉 UIPageViewController 回弹效果

**Comment by lishangjing-spec** [comment]
因为我看原代码用的 UIPageViewController , 这个东西不能直接设置 bounce 去禁止回弹

**Comment by mengxianliang** [comment]
XLPageViewController.m里第120行获取了一个UIScrollView,给这个ScrollView设置bounce可以禁止回弹.
这个ScrollView是UIPageviewController自带的ScrollView.

**Comment by lishangjing-spec** [comment]
这个我设置过了, 设置以后发现就滑不动了. UIPageViewController 应该不能这么玩 , 所以我才用我上面说的方法去解决了. 但是又有点怕出bug.

**Comment by mengxianliang** [comment]
//试试这样设置一下

    CGFloat contentX = scrollView.contentOffset.x;
    CGFloat width = scrollView.bounds.size.width;
    if (self.selectedIndex == 0) {
        if (contentX <= width && scrollView.isDragging) {
            scrollView.bounces = NO;
        }else {
            scrollView.bounces = YES;
        }
    }else if (self.selectedIndex == [self numberOfPage] - 1) {
        if (contentX >= width && scrollView.isDragging) {
            scrollView.bounces = NO;
        }else {
            scrollView.bounces = YES;
        }
    }else {
        scrollView.bounces = YES;
    }
