### ISSUE TITLE
期待添加swift版本

### ISSUE THREAD

**Issue by xljhd** [mengxianliang/XLPageViewController#15]

**Comment by mengxianliang** [comment]
好 有时间我添加一下

**Comment by xljhd** [comment]
谢谢大佬回复





------------------ 原始邮件 ------------------
发件人: XianLiang Meng <notifications@github.com&gt;
发送时间: 2019年11月21日 08:58
收件人: mengxianliang/XLPageViewController <XLPageViewController@noreply.github.com&gt;
抄送: 嘎嘎嘎 <728599123@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[mengxianliang/XLPageViewController] 期待添加swift版本 (#15)
