### ISSUE TITLE
请问如何返回呢？

### ISSUE THREAD

**Issue by czpc** [mengxianliang/XLPageViewController#17]
在和FDFullscreenPopGesture 配套使用的时候。如何拉动到最左边的时候。返回上级呢？

**Comment by mengxianliang** [comment]
只能禁用pageVC的滚动了，现在没有更好的办法。

**Comment by mengxianliang** [comment]
已兼容全屏返回手势，将pageVC的needRespondFullScreenBackGesture设为YES即可。

**Comment by czpc** [comment]
好的。谢谢
