### ISSUE TITLE
在进行频繁的左右活动的时候，会出现页面混乱现象

### ISSUE THREAD

**Issue by LiuQiang11** [mengxianliang/XLPageViewController#2]
//获取当前vc和当前标题
    UIViewController *currentVC = self.pageVC.viewControllers.firstObject;
    NSString *currentTitle = currentVC.title;

    NSString *targetTitle = [self titleForIndex:index];

    //如果和当前位置一样，则返回当前vc
    if ([currentTitle isEqualToString:targetTitle]) {
        return currentVC;
    }

    //如果之前显示过，则从内存中读取
    for (UIViewController *vc in self.shownVCArr) {
        if ([vc.title isEqualToString:targetTitle]) {
            return vc;
        }
    }

上面这个段代码导致的

所以我提供的解决方案是：

 //如果之前显示过，则从内存中读取
    if (index < self.shownVCArr.count) {
        UIViewController *vc = self.shownVCArr[index];
        return vc;
    }

**Comment by mengxianliang** [comment]
好的 谢谢提出问题。
但是您的方法可能行不通，因为shownVCArr是缓存已经显示过的视图控制器，存储是没有顺序的。不能通过index的方式来取。

**Comment by LiuQiang11** [comment]
好的，谢谢，我没有考虑清晰。

**Comment by OyesOnoOmg** [comment]
> 好的 谢谢提出问题。
> 但是您的方法可能行不通，因为shownVCArr是缓存已经显示过的视图控制器，存储是没有顺序的。不能通过index的方式来取。

那怎么解决啊  这个bug

**Comment by mengxianliang** [comment]
这个问题已经解决了，可以重新下载Demo看一下。
