### ISSUE TITLE
右滑返回手势与scrollView的滑动手势冲突

### ISSUE THREAD

**Issue by sdwangxianwen** [mengxianliang/XLPageViewController#21]
应该不止我一个人自定义了nav,并添加了全屏右滑返回的手势吧，如果加了就会和你这个srollview的手势冲突，需要创建一个scrollView的分类解决这个问题，希望考虑添加上

**Comment by ZJF-Coder** [comment]
如果项目中引用了其他管理全屏右滑返回的手势，在作者的控制器XLPageViewController里面会手势返回不了页面，请问要如何处理？

**Comment by mengxianliang** [comment]
已兼容全屏返回手势，将pageVC的needRespondFullScreenBackGesture设为YES即可。
