### ISSUE TITLE
为什么第一个标题不加载对应的页面啊,切换标题之后就可以了

### ISSUE THREAD

**Issue by syqaxldy** [mengxianliang/XLPageViewController#28]
![image](https://user-images.githubusercontent.com/13041822/77608431-1ea29c80-6f58-11ea-9a5f-5930e15e8e8a.png)
![image](https://user-images.githubusercontent.com/13041822/77608452-324e0300-6f58-11ea-855a-42ac82cfa4ae.png)

**Comment by mengxianliang** [comment]
需要在刷新后添加一句更新选中位置的代码，就会加载对应的界面。
```objc
//第一步，先刷新数据
[self.pageViewController reloadData];
//第二步，更新选中位置，这里固定为0，可根据自己的业务逻辑，自行设定
self.pageViewController.selectedIndex = 0;
```
