### ISSUE TITLE
第一次通过右侧按钮设置selectedIndex过大时，下方的指示器无法正常移动

### ISSUE THREAD

**Issue by yuanliangYL** [mengxianliang/XLPageViewController#29]

**Comment by mengxianliang** [comment]
麻烦可以再详细的描述一下问题吗，右侧按钮指的是频道管理吗，如果是selectedIndex超出标题最大数的话，会抛出异常的。

**Comment by yuanliangYL** [comment]
![51585798389_ pic](https://user-images.githubusercontent.com/18209116/78207968-c3cbf080-74d5-11ea-92d6-1d412f7e87ad.jpg)
在titleView未滚动的情况下，直接通过外部按钮设置selectedIndex（在标题范围内）过大，下方的指示器异常移动。

**Comment by mengxianliang** [comment]
已经处理好了，更新一下代码试一下吧。
