### ISSUE TITLE
请求下来的标题如果超过7个 最后2个就点不到 也滑动不到最后2个标题

### ISSUE THREAD

**Issue by syqaxldy** [mengxianliang/XLPageViewController#31]
@"撒大声地",@"撒大声地" ,@"撒大声地",@"测试",@"测试",@"测试",@"测试",@"测试"
XLPageViewControllerConfig *config = [XLPageViewControllerConfig defaultConfig];
    config.titleSpace = 10;
    config.titleViewInset = UIEdgeInsetsMake(0, 10, 0, 10);
    self.pageViewController = [[XLPageViewController alloc] initWithConfig:config];
   
    self.pageViewController.view.frame = CGRectMake(0, NavBar_Height, kWidth, kHeight-NavBar_Height);
    self.pageViewController.delegate = self;
    self.pageViewController.dataSource = self;
 [self addChildViewController:self.pageViewController];
    [self.view addSubview:self.pageViewController.view];
![123123](https://user-images.githubusercontent.com/13041822/80439151-71e18380-8938-11ea-9852-5e2efefac313.gif)

**Comment by mengxianliang** [comment]
```objc
pageViewControllerNumberOfPage
```
请求之后，这个代理方法里的数据更新了吗？

**Comment by syqaxldy** [comment]
更新了啊
- (NSInteger)pageViewControllerNumberOfPage {
    return self.enabledTitles.count;
}
![B895E2AF-EB61-4C7B-AD04-406209164CBB](https://user-images.githubusercontent.com/13041822/80443652-4794c380-8942-11ea-9bb1-6fbb17cbfdb3.png)

**Comment by mengxianliang** [comment]
方便把的话可以把出错的Demo发我一下，我看看。
