### ISSUE TITLE
demo无此问题，个人项目中自定义全屏导航，多级嵌套出现，index=0是的子类滑动，直接响应的是父类导航栏的滑动

### ISSUE THREAD

**Issue by biny-an** [mengxianliang/XLPageViewController#33]

**Comment by mengxianliang** [comment]
能否提供一下测试的Demo，或者录屏，看一下效果。

**Comment by biny-an** [comment]
[1589009694550314.mp4.zip](https://github.com/mengxianliang/XLPageViewController/files/4602931/1589009694550314.mp4.zip)

**Comment by mengxianliang** [comment]
你可以更新一下代码，昨天针对这个问题做了些优化。
needRespondFullScreenBackGesture这个属性默认是关闭的，关闭时不会响应全屏返回。如果打开会在第一页响应滑动返回。

**Comment by biny-an** [comment]
我开启了这个属性，出现了视频里面那种问题，我现在把这个属性关闭之后。多级嵌套正常滑动，不过当前界面不会侧滑返回了。

**Comment by mengxianliang** [comment]
好的，优化了一下手势冲突的解决办法，

如果你用的全屏返回方案是FDFullscreenPopGesture

设置如下代码：
```objc
self.pageViewController.respondOtherGestureDelegateClassList = @[@"_FDFullscreenPopGestureRecognizerDelegate"];
```

如果是其它方案，找到手势delegate的类名，添加到这个集合里。

**Comment by biny-an** [comment]
通过你这种方法，已解决。非常感谢~！

**Comment by mengxianliang** [comment]
不客气～
