### ISSUE TITLE
添加MJRefresh下拉刷新和上拉加载更多 刷新视图不能收起和停止

### ISSUE THREAD

**Issue by Bob-GGB** [mengxianliang/XLPageViewController#35]
添加MJRefresh下拉刷新和上拉加载更多 刷新视图不能收起和停止 @mengxianliang

**Comment by mengxianliang** [comment]
方便的话提供一下有问题的Demo，看一下效果。

**Comment by Bob-GGB** [comment]
![image](https://user-images.githubusercontent.com/20783580/82188925-2f044180-9921-11ea-8be5-5321049d2633.png)
这是图片

**Comment by Bob-GGB** [comment]
![image](https://user-images.githubusercontent.com/20783580/82189105-738fdd00-9921-11ea-8304-dc9db43381fb.png)

**Comment by Bob-GGB** [comment]
我在服务器返回结果的回调里面 也做了 [self.listTableView.mj_header endRefreshing]; 但是没有作用

**Comment by mengxianliang** [comment]
会不会是在调用endRefreshing方法时不在主线程，在调用endRefreshing时先打印一下当前线程看一下，如果不是主线程，调整到主线程调用试一下。

**Comment by Bob-GGB** [comment]
我试过了 在主线程调用    dispatch_async(dispatch_get_main_queue(), ^{
               [self.listTableView.mj_header endRefreshing];
           }); 还是不行

**Comment by Bob-GGB** [comment]
问题找到了 是tableView懒加载的问题导致的 谢谢你的回复

**Comment by mengxianliang** [comment]
不客气
