### ISSUE TITLE
关于侧滑失效和弹簧效果

### ISSUE THREAD

**Issue by XWXGitHub** [mengxianliang/XLPageViewController#38]
//滑动开关
- (void)setScrollEnabled:(BOOL)scrollEnabled {
    _scrollEnabled = scrollEnabled;
    self.scrollView.scrollEnabled = scrollEnabled;
}
当我设置self.pageViewController.scrollEnabled = NO;时，第一次加载确实是不能滑动，然后我点击其它title时，既然发现又可以滑动了。

偶然的情况下：
在我想处理侧滑第1个或者最后一个tiltle时，控制侧滑没有弹簧效果时，发现实现了禁止滑动的操作，没有上面的bug了。代码如下
//滑动开关
- (void)setScrollEnabled:(BOOL)scrollEnabled {
    _scrollEnabled = scrollEnabled;
    self.scrollView.bounces = scrollEnabled;
}

不知道是不是我代码的原因，还请您查阅下呢。最后，想问下作者您的代码能实现侧滑第1个或者最后一个tiltle时，控制侧滑没有弹簧效果(第0个或者最后一个title时，侧滑还是会有滑动一定距离然后有弹回的效果)吗？

**Comment by mengxianliang** [comment]
1、点击标题切换后禁用滚动失效这个bug已经解决了。
2、添加了bounces属性，如需禁用滑倒左右边缘时的回弹效果，可设置bounces为NO。
```objc
pageViewController. bounces = NO;
```

**Comment by XWXGitHub** [comment]
十分感谢，没有问题，非常棒的一个组件。期待您的更多优秀作品。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "XianLiang&nbsp;Meng"; 
发送时间: 2020年6月1日(星期一) 中午11:09
收件人: "mengxianliang/XLPageViewController";
抄送: "XWXGitHub"<1040592437@qq.com>;"Author";
主题: Re: [mengxianliang/XLPageViewController] 关于侧滑失效和弹簧效果 (#38)





 
1、点击标题切换后禁用滚动失效这个bug已经解决了。
 2、添加了bounces属性，如需禁用滑倒左右边缘时的回弹效果，可设置bounces为NO。
 pageViewController. bounces = NO;
 
&mdash;
