### ISSUE TITLE
快速滑动导致页面混乱的问题

### ISSUE THREAD

**Issue by ioslhf** [mengxianliang/XLPageViewController#4]
我的项目里面用了这个， 出现快速滑动页面混乱的情况，  没有找到问题的根本原因。 所以就用了一个比较笨的方法，  就是在左右滚动的动画开始的时候 禁用交互，动画结束的时候再打开。 这样能暂时解决一下这个问题，  希望作者能抽空改一下这个bug  *_*。

#pragma mark 开始滚动时 禁止交互,  防止滚动还未结束时 抬手重新滚动 导致的bug    
- (void)scrollViewWillBeginDecelerating:(UIScrollView *)scrollView{
    self.contentView.userInteractionEnabled = NO;
}
- (void)scrollViewDidEndDecelerating:(UIScrollView *)scrollView{
    self.contentView.userInteractionEnabled = YES;
}

**Comment by sizhugongzi** [comment]
请问一下这个写在什么地方

**Comment by mengxianliang** [comment]
这个问题已经解决了，可以重新下载Demo看一下
