### ISSUE TITLE
延迟加载数据第一页不显示 滑动崩溃 reason: 'Invalid parameter not satisfying: [views count] == 3'

### ISSUE THREAD

**Issue by QYX-Ghost** [mengxianliang/XLPageViewController#46]
延迟加载数据第一页不显示 滑动崩溃

伪代码

`[self addChildViewController: self.pageController];`
`[self.view addSubView:self.pageController.view];`
`dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{`
`    // 延迟加载数据`
`    [self.pageController reloadData];`
`});`

必现BUG
延迟加载后设置`selectedIndex = 0`也没有效果

**Comment by 13546490786** [comment]
我也碰到一样的问题，请作者尽快解决此问题

**Comment by 13546490786** [comment]
可能是这里引起的，麻烦尽快解决这个问题
*** Assertion failure in -[_UIQueuingScrollView _replaceViews:updatingContents:adjustContentInsets:animated:], /Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3920.31.102/_UIQueuingScrollView.m:395

**Comment by 13546490786** [comment]
我换了个思路，等数据加载回来后再初始化instance，暂时处理了这种场景

**Comment by mengxianliang** [comment]
已经修改好了，请更新一下代码。
需要先执行reloadData方法，设置selectedIndex。
