### ISSUE TITLE
XLPageViewController的dealloc方法没走

### ISSUE THREAD

**Issue by hzz2020** [mengxianliang/XLPageViewController#47]
XLPageViewController.m文件138行
在block中应该都使用weakSelf
self.scrollView.xl_otherGestureRecognizerBlock = ^BOOL(UIGestureRecognizer * _Nonnull otherGestureRecognizer) {
        return weakSelf.selectedIndex == 0 && [weakSelf.respondOtherGestureDelegateClassList containsObject:NSStringFromClass(otherGestureRecognizer.delegate.class)];
    };

**Comment by mengxianliang** [comment]
感谢指出，已修复。
