### ISSUE TITLE
系统侧滑无法实现，needRespondFullScreenBackGesture这个属性不存在

### ISSUE THREAD

**Issue by 1036938520** [mengxianliang/XLPageViewController#61]
添加：pageViewController.respondOtherGestureDelegateClassList = @[@"interactivePopGestureRecognizer"];进行侧滑没有效果，needRespondFullScreenBackGesture这个属性也不存在。能否告知具体应该怎么写么？

**Comment by mengxianliang** [comment]
要实现全屏滑动返回，您还需要集成[FDFullscreenPopGesture](https://github.com/forkingdog/FDFullscreenPopGesture)，然后添加配置：
```objc
self.pageViewController.respondOtherGestureDelegateClassList = @[@"_FDFullscreenPopGestureRecognizerDelegate"];
```
