### ISSUE TITLE
需要手动触发循环滚动或者循环滑动。能否增加这个功能。

### ISSUE THREAD

**Issue by alucardulad** [mengxianliang/XLPageViewController#64]
需要手动触发循环滚动或者循环滑动。能否增加这个功能。

**Comment by mengxianliang** [comment]
暂时没有计划加这个功能，可以参考这个项目，里面有循环滑动的实现思路 [XLCycleCollecitonView](https://github.com/mengxianliang/XLCycleCollectionView)

**Comment by alucardulad** [comment]
好的。谢谢咧、
