### ISSUE TITLE
全屏手势的问题

### ISSUE THREAD

**Issue by heavy-metal** [mengxianliang/XLPageViewController#7]
因为我的项目里面都是全屏右滑返回，需要拿到您代码里面内容的scrollview，让它继承CustomScrollView，实现一个代理方法触发，让内容的scrollview允许多手势。。从而实现滑动视图和全屏手势的冲突问题。现在的问题是:没找到相应的scrollview，暂时也没有时间慢慢去研究您写的代码。。

class CustomScrollView: UIScrollView {

}
extension CustomScrollView : UIGestureRecognizerDelegate {
    func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        if otherGestureRecognizer.state == UIGestureRecognizerState.began && self.contentOffset.x == 0 {
            return true
        }
        return false
    }
}

**Comment by mengxianliang** [comment]
Scrollview在XLPageViewController.m里
找到这段代码
for (UIScrollView *scrollView in self.pageVC.view.subviews) {
        if ([scrollView isKindOfClass:[UIScrollView class]]) {
            scrollView.delegate = self;
        }
    }

**Comment by heavy-metal** [comment]
我需要找到你初始化创建scrollView的地方

**Comment by heavy-metal** [comment]
发现了一个bug，快速滑动过程，有按钮normal状态下的颜色会变成selected的颜色（没有选中它也是selected的颜色）

**Comment by mengxianliang** [comment]
我用的是UIPageViewController，scrollView是UIPageViewController的私有属性，并不是手动创建的。
昨天更新了一下代码，快速滑动的问题已经解决了，你可以重新下载一下代码看看效果。

**Comment by heavy-metal** [comment]
刚下载的，你可以检验一下，normal的颜色和selected的颜色你换一下，100%会出现bug

**Comment by heavy-metal** [comment]
希望能实现一下全屏的滑动返回功能，谢谢

**Comment by mengxianliang** [comment]
我刚更新了一下代码，修正一个属性叫scrollEnabled，创建分页控制器时可以把这个属性设为NO，会禁用滚动。就不会和全屏滑动返回冲突了。
