### ISSUE TITLE
self.pageViewController.selectedIndex用来跳转异常

### ISSUE THREAD

**Issue by programmerElephant** [mengxianliang/XLPageViewController#8]
但有很多tabbar的时候，我初始化想直接进入第x个tabbar时使用self.pageViewController.selectedIndex异常，可以复线。比如你创建15个tabbar，然后self.pageViewController.selectedIndex = 10，显示异常

**Comment by mengxianliang** [comment]
已经解决了

**Comment by Mandyhold** [comment]
已经解决了吗，我初始化选中第二个tab，然后动手切换tab的时候会闪退，滑动切换也会闪退Printing description of reason:
MASLayoutConstraint constant is not finite!  That's illegal.  constant:nan firstAnchor:<NSLayoutDimension:0x283336ac0 "UIImageView:0x10a278900.height"> secondAnchor:(null)
